/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/common/403': RouteRecordInfo<'/common/403', '/common/403', Record<never, never>, Record<never, never>>,
    '/common/forgot-password': RouteRecordInfo<'/common/forgot-password', '/common/forgot-password', Record<never, never>, Record<never, never>>,
    '/common/login': RouteRecordInfo<'/common/login', '/common/login', Record<never, never>, Record<never, never>>,
    '/common/nopermissions': RouteRecordInfo<'/common/nopermissions', '/common/nopermissions', Record<never, never>, Record<never, never>>,
    '/common/register': RouteRecordInfo<'/common/register', '/common/register', Record<never, never>, Record<never, never>>,
    '/file/': RouteRecordInfo<'/file/', '/file', Record<never, never>, Record<never, never>>,
    '/PaperSquare': RouteRecordInfo<'/PaperSquare', '/PaperSquare', Record<never, never>, Record<never, never>>,
    '/user/profile': RouteRecordInfo<'/user/profile', '/user/profile', Record<never, never>, Record<never, never>>,
  }
}
